baseURL = "http://example.org/"
languageCode = "en-us"
title = "Cucumber Documentation"
theme = "cucumber-hugo"

pygmentsUseClassic = true
pygmentsCodeFences = true
pygmentsUseClasses = true

[[menu.bdd]]
    weight = 1
    name = "Overview"
    identifier = "The essence of Behaviour-Driven Development"
    url = "/bdd/"
[[menu.bdd]]
    weight = 10
    name = "BDD Tutorial"
    identifier = "Build an application, guided by Cucumber"
    url = "/bdd-tutorial/"
[[menu.bdd]]
    weight = 20
    name = "Example Mapping"
    identifier = "Breaking down user stories into examples"
    url = "/example-mapping/"
[[menu.bdd]]
    weight = 30
    name = "Who Does What"
    identifier = "Programmers, Testers, Domain experts and more"
    url = "/who-does-what/"


[[menu.support]]
    weight = "10"
    name = "Get in touch"
    identifier = "How to reach us"
    url = "/about/get-in-touch/"
[[menu.support]]
    weight = "20"
    name = "Contributing to Cucumber"
    identifier = "Help make Cucumber better"
    url = "/about/contributing/"
[[menu.support]]
    weight = "30"
    name = "Contributing to Documentation"
    identifier = "Help make these docs better"
    url = "/about/contributing-to-documentation/"
[[menu.support]]
    weight = 50
    name = "---"
[[menu.support]]
    weight = "60"
    name = "Blog posts"
    identifier = "Blog posts on Cucumber and BDD"
    url = "/about/blog-posts/"
[[menu.support]]
    weight = "70"
    name = "Related Tools"
    identifier = "Tools to use with Cucumber"
    url = "/about/related-tools/"
[[menu.support]]
    weight = "80"
    name = "Projects"
    identifier = "Projects using Cucumber"
    url = "/about/projects-using-cucumber/"
